logger:
    version: 1
    disable_existing_loggers: False
    formatters:
        default:
            format: '[%(asctime)s] [%(process)s] [%(name)s] [%(levelname)s] %(message)s'
            datefmt: '%Y-%m-%dT%H:%M:%S'
    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: default
    root:
        level: DEBUG
        handlers: [console]
